// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGH9ulShJyT7ZimPttUTZkB1M_QJlYkOo',
    appId: '1:740232602057:web:5b3a3317548f0ff90c0818',
    messagingSenderId: '740232602057',
    projectId: 'comp5b-24-70c18',
    authDomain: 'comp5b-24-70c18.firebaseapp.com',
    storageBucket: 'comp5b-24-70c18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEaZRTakGYL0GZQHKAS74lT5ilKirxpw',
    appId: '1:740232602057:android:c8a0f3da37e2e31c0c0818',
    messagingSenderId: '740232602057',
    projectId: 'comp5b-24-70c18',
    storageBucket: 'comp5b-24-70c18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwA2q9MzB9suWXXCuwVDexIDFkBVR97z0',
    appId: '1:740232602057:ios:06af0bae02e336340c0818',
    messagingSenderId: '740232602057',
    projectId: 'comp5b-24-70c18',
    storageBucket: 'comp5b-24-70c18.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
